[rocket]
address = "0.0.0.0"
port = 5000
keep_alive = 0
secret_key = "Iu68DGtvdKmffVt8bxE7ULSAfnUzef+T9bQQuGZ0wII="

[database]
address = "127.0.0.1"
port = 5432
username = "dev"
password = "dev"
database = "smart-home"
pool_size = 5

