[build]
target = "aarch64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
runner = "./runner.sh"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
runner = "./runner.sh"
